// The 200 levels added in version 1.1: [fr, en, es, category, solution, difficulty 1–3].
module.exports = [
  // Sport
  ['Football', 'Football', 'Fútbol', 'sport', '⚽🥅', 1],
  ['Basket', 'Basketball', 'Baloncesto', 'sport', '🏀👟', 1],
  ['Tennis', 'Tennis', 'Tenis', 'sport', '🎾🏟️', 1],
  ['Rugby', 'Rugby', 'Rugby', 'sport', '🏉💪', 1],
  ['Golf', 'Golf', 'Golf', 'sport', '⛳🧢', 1],
  ['Ski', 'Skiing', 'Esquí', 'sport', '⛷️❄️', 1],
  ['Natation', 'Swimming', 'Natación', 'sport', '🏊💦', 1],
  ['Boxe', 'Boxing', 'Boxeo', 'sport', '🥊🔔', 1],
  ['Surf', 'Surfing', 'Surf', 'sport', '🏄🌊', 1],
  ['Formule 1', 'Formula 1', 'Fórmula 1', 'sport', '🏎️🏁', 1],
  ['Bowling', 'Bowling', 'Bolos', 'sport', '🎳🍺', 1],
  ['Escalade', 'Climbing', 'Escalada', 'sport', '🧗🪢', 1],
  ['Hockey sur glace', 'Ice hockey', 'Hockey sobre hielo', 'sport', '🏒🧊', 1],
  ['Baseball', 'Baseball', 'Béisbol', 'sport', '⚾🧢🇺🇸', 1],
  ['Pêche', 'Fishing', 'Pesca', 'sport', '🎣🐟', 1],
  ['Ping-pong', 'Table tennis', 'Ping-pong', 'sport', '🏓🇨🇳', 1],
  ['Tour de France', 'Tour de France', 'Tour de Francia', 'sport', '🚴🇫🇷🟡', 2],
  ['Jeux olympiques', 'Olympic Games', 'Juegos Olímpicos', 'sport', '🥇🔥🌍', 2],
  ['Coupe du monde', 'World Cup', 'Mundial', 'sport', '⚽🏆🌍', 2],
  ['Marathon', 'Marathon', 'Maratón', 'sport', '🏃⏱️🏅', 2],
  // Jobs
  ['Pompier', 'Firefighter', 'Bombero', 'job', '🚒🔥', 1],
  ['Policier', 'Police officer', 'Policía', 'job', '🚓🚨', 1],
  ['Médecin', 'Doctor', 'Médico', 'job', '🩺💊', 1],
  ['Cuisinier', 'Chef', 'Cocinero', 'job', '🍳🔪', 1],
  ['Boulanger', 'Baker', 'Panadero', 'job', '🥖🥐', 1],
  ['Astronaute', 'Astronaut', 'Astronauta', 'job', '🚀🌕', 1],
  ['Pilote de ligne', 'Airline pilot', 'Piloto de avión', 'job', '✈️👨‍✈️', 1],
  ['Dentiste', 'Dentist', 'Dentista', 'job', '🦷👨‍⚕️', 1],
  ['Facteur', 'Mail carrier', 'Cartero', 'job', '✉️🚲', 1],
  ['Jardinier', 'Gardener', 'Jardinero', 'job', '🌻🪴💧', 1],
  ['Agriculteur', 'Farmer', 'Agricultor', 'job', '🚜🌾', 1],
  ['Coiffeur', 'Hairdresser', 'Peluquero', 'job', '✂️💈', 1],
  ['Professeur', 'Teacher', 'Profesor', 'job', '📚✏️🏫', 1],
  ['Vétérinaire', 'Vet', 'Veterinario', 'job', '🐶🩺', 1],
  ['Plombier', 'Plumber', 'Fontanero', 'job', '🔧🚽', 1],
  ['Peintre', 'Painter', 'Pintor', 'job', '🎨🖌️', 1],
  ['Scientifique', 'Scientist', 'Científico', 'job', '🔬🧪', 1],
  ['Magicien', 'Magician', 'Mago', 'job', '🎩🐇🪄', 1],
  ['Détective', 'Detective', 'Detective', 'job', '🕵️🔦👣', 2],
  ['Juge', 'Judge', 'Juez', 'job', '⚖️🔨', 2],
  // Tales and legends
  ['Le Petit Chaperon rouge', 'Little Red Riding Hood', 'Caperucita Roja', 'tale', '🔴🐺👧', 1],
  ['Les Trois Petits Cochons', 'The Three Little Pigs', 'Los tres cerditos', 'tale', '🐷🐺🧱', 1],
  ['La Belle au bois dormant', 'Sleeping Beauty', 'La Bella Durmiente', 'tale', '👸💤🏰', 1],
  ['La Petite Sirène', 'The Little Mermaid', 'La Sirenita', 'tale', '🧜‍♀️🐚🦀', 1],
  ['Robin des Bois', 'Robin Hood', 'Robin Hood', 'tale', '🏹🌳💰', 1],
  ['Le Chat botté', 'Puss in Boots', 'El Gato con Botas', 'tale', '🐱👢🎩', 1],
  ['Alice au pays des merveilles', 'Alice in Wonderland', 'Alicia en el país de las maravillas', 'tale', '👧🐇🫖', 1],
  ['La Belle et la Bête', 'Beauty and the Beast', 'La Bella y la Bestia', 'tale', '🌹👸👹', 1],
  ['Dracula', 'Dracula', 'Drácula', 'tale', '🧛🩸🦇', 1],
  ['Le Vilain Petit Canard', 'The Ugly Duckling', 'El patito feo', 'tale', '🦆🦢', 1],
  ['Cupidon', 'Cupid', 'Cupido', 'tale', '👼🏹💘', 1],
  ['Peter Pan', 'Peter Pan', 'Peter Pan', 'tale', '🧚👦🐊', 2],
  ['Hansel et Gretel', 'Hansel and Gretel', 'Hansel y Gretel', 'tale', '🍬🏠🧙‍♀️', 2],
  ['Jack et le haricot magique', 'Jack and the Beanstalk', 'Jack y las habichuelas mágicas', 'tale', '🌱☁️👹', 2],
  ["Boucle d'or", 'Goldilocks', 'Ricitos de Oro', 'tale', '👱‍♀️🐻🥣', 2],
  ['Frankenstein', 'Frankenstein', 'Frankenstein', 'tale', '🧟⚡🔩', 2],
  ['Le Roi Arthur', 'King Arthur', 'El Rey Arturo', 'tale', '🗡️🪨👑', 2],
  ['Le Monstre du Loch Ness', 'The Loch Ness Monster', 'El monstruo del lago Ness', 'tale', '🦕🏞️🔍', 2],
  ['Hercule', 'Hercules', 'Hércules', 'tale', '💪🦁🏛️', 2],
  ['Le Petit Prince', 'The Little Prince', 'El Principito', 'tale', '👦🌹🪐', 2],
  // Home and objects
  ['Réveil', 'Alarm clock', 'Despertador', 'home', '⏰🛏️', 1],
  ['Aspirateur', 'Vacuum cleaner', 'Aspiradora', 'home', '🧹🔌💨', 1],
  ['Grille-pain', 'Toaster', 'Tostadora', 'home', '🍞🔥🔌', 1],
  ['Lampe', 'Lamp', 'Lámpara', 'home', '💡🔌', 1],
  ['Canapé', 'Sofa', 'Sofá', 'home', '🛋️📺', 1],
  ['Brosse à dents', 'Toothbrush', 'Cepillo de dientes', 'home', '🦷🪥', 1],
  ['Douche', 'Shower', 'Ducha', 'home', '🚿🧼', 1],
  ['Bain moussant', 'Bubble bath', 'Baño de espuma', 'home', '🛁🦆🧴', 1],
  ['Lit', 'Bed', 'Cama', 'home', '🛏️💤', 1],
  ['Ordinateur', 'Computer', 'Ordenador', 'home', '💻🖱️⌨️', 1],
  ['Smartphone', 'Smartphone', 'Móvil', 'home', '📱📶🔋', 1],
  ['Cheminée', 'Fireplace', 'Chimenea', 'home', '🔥🪵🏠', 1],
  ['Piscine', 'Swimming pool', 'Piscina', 'home', '🩱☀️💦', 1],
  ['Poubelle', 'Trash can', 'Cubo de basura', 'home', '🗑️🍌', 1],
  ['Sonnette', 'Doorbell', 'Timbre', 'home', '🔔🚪', 1],
  ['Machine à laver', 'Washing machine', 'Lavadora', 'home', '👕💧🌀', 2],
  ['Frigo', 'Fridge', 'Nevera', 'home', '🥛🧊🚪', 2],
  ['Télécommande', 'Remote control', 'Mando a distancia', 'home', '📺👆🔋', 2],
  ['Micro-ondes', 'Microwave', 'Microondas', 'home', '🍲⏲️⚡', 2],
  ['Ventilateur', 'Fan', 'Ventilador', 'home', '🌀🥵', 2],
  // Holidays and parties
  ['Noël', 'Christmas', 'Navidad', 'party', '🎄🎅🎁', 1],
  ['Halloween', 'Halloween', 'Halloween', 'party', '🎃👻🍬', 1],
  ['Pâques', 'Easter', 'Pascua', 'party', '🐰🥚🍫', 1],
  ['Anniversaire', 'Birthday', 'Cumpleaños', 'party', '🎂🎈🎁', 1],
  ['Mariage', 'Wedding', 'Boda', 'party', '💍👰💒', 1],
  ['Nouvel An', 'New Year', 'Año Nuevo', 'party', '🎆🥂🕛', 1],
  ['Saint-Valentin', 'Valentine’s Day', 'San Valentín', 'party', '💘🌹🍫', 1],
  ['Pique-nique', 'Picnic', 'Pícnic', 'party', '🧺🥪🌳', 1],
  ['Barbecue', 'Barbecue', 'Barbacoa', 'party', '🍖🔥🌭', 1],
  ['Concert', 'Concert', 'Concierto', 'party', '🎤🎸🎟️', 1],
  ['Carnaval', 'Carnival', 'Carnaval', 'party', '🎭🎊🥁', 2],
  ['Nouvel An chinois', 'Chinese New Year', 'Año Nuevo chino', 'party', '🐉🧧🏮', 2],
  ['Fête des morts mexicaine', 'Day of the Dead', 'Día de Muertos', 'party', '💀🌼🇲🇽', 2],
  ['Thanksgiving', 'Thanksgiving', 'Acción de Gracias', 'party', '🦃🥧🇺🇸', 2],
  ['Saint-Patrick', 'St. Patrick’s Day', 'San Patricio', 'party', '☘️🍺🇮🇪', 2],
  ['Oktoberfest', 'Oktoberfest', 'Oktoberfest', 'party', '🍺🥨🇩🇪', 2],
  ['Le 14 Juillet', 'Bastille Day', 'Día de la Bastilla', 'party', '🇫🇷🎆', 2],
  ['Soirée pyjama', 'Sleepover', 'Fiesta de pijamas', 'party', '🛌🍕🎬', 2],
  ["Poisson d'avril", 'April Fools’ Day', 'Día de los Inocentes', 'party', '🐟📅😜', 2],
  ['Diwali', 'Diwali', 'Diwali', 'party', '🪔🎆🇮🇳', 3],
  // Landmarks
  ['Tour Eiffel', 'Eiffel Tower', 'Torre Eiffel', 'place', '🗼🇫🇷', 1],
  ['Statue de la Liberté', 'Statue of Liberty', 'Estatua de la Libertad', 'place', '🗽👑🔥', 1],
  ['Pyramides de Gizeh', 'Pyramids of Giza', 'Pirámides de Guiza', 'place', '🔺🐫☀️', 1],
  ['Grande Muraille de Chine', 'Great Wall of China', 'Gran Muralla China', 'place', '🧱🇨🇳🐉', 1],
  ['Big Ben', 'Big Ben', 'Big Ben', 'place', '🕰️🇬🇧🔔', 1],
  ['Hollywood', 'Hollywood', 'Hollywood', 'place', '🎬⭐🌴', 1],
  ['Las Vegas', 'Las Vegas', 'Las Vegas', 'place', '🎰🃏🌵', 1],
  ['Venise', 'Venice', 'Venecia', 'place', '🛶🇮🇹🎭', 1],
  ['Colisée', 'Colosseum', 'Coliseo', 'place', '🏟️🇮🇹🦁', 2],
  ['Taj Mahal', 'Taj Mahal', 'Taj Mahal', 'place', '🕌🇮🇳💕', 2],
  ['Tour de Pise', 'Leaning Tower of Pisa', 'Torre de Pisa', 'place', '🇮🇹🗼↘️', 2],
  ['Mont-Saint-Michel', 'Mont-Saint-Michel', 'Monte Saint-Michel', 'place', '🏰🌊🇫🇷', 2],
  ['Christ Rédempteur', 'Christ the Redeemer', 'Cristo Redentor', 'place', '✝️🇧🇷⛰️', 2],
  ['Opéra de Sydney', 'Sydney Opera House', 'Ópera de Sídney', 'place', '🎭🇦🇺⛵', 2],
  ['Mont Everest', 'Mount Everest', 'Monte Everest', 'place', '🏔️❄️🇳🇵', 2],
  ['Château de Versailles', 'Palace of Versailles', 'Palacio de Versalles', 'place', '👑🪞🇫🇷', 2],
  ['Musée du Louvre', 'Louvre Museum', 'Museo del Louvre', 'place', '🖼️🔺🇫🇷', 2],
  ['Stonehenge', 'Stonehenge', 'Stonehenge', 'place', '🪨🌄🇬🇧', 3],
  ['Machu Picchu', 'Machu Picchu', 'Machu Picchu', 'place', '🦙🏔️🇵🇪', 3],
  ['Sagrada Família', 'Sagrada Família', 'Sagrada Familia', 'place', '⛪🇪🇸🏗️', 3],
  // Movies
  ['E.T.', 'E.T.', 'E.T.', 'movie', '👽🚲🌕', 1],
  ['Superman', 'Superman', 'Superman', 'movie', '🦸‍♂️🌍💪', 1],
  ['Charlie et la Chocolaterie', 'Charlie and the Chocolate Factory', 'Charlie y la fábrica de chocolate', 'movie', '🍫🏭🎫', 1],
  ['Les Minions', 'Minions', 'Los Minions', 'movie', '🟡👖🍌', 1],
  ['Kung Fu Panda', 'Kung Fu Panda', 'Kung Fu Panda', 'movie', '🐼🥋🥟', 1],
  ['Coco', 'Coco', 'Coco', 'movie', '💀🎸👦', 1],
  ['Madagascar', 'Madagascar', 'Madagascar', 'movie', '🦓🦒🐧', 1],
  ['Le Parrain', 'The Godfather', 'El Padrino', 'movie', '🤵🌹🇮🇹', 2],
  ['Mary Poppins', 'Mary Poppins', 'Mary Poppins', 'movie', '☂️👜🌬️', 2],
  ['Vice-Versa', 'Inside Out', 'Del revés', 'movie', '😭😡🧠', 2],
  // Series
  ["Bob l'éponge", 'SpongeBob', 'Bob Esponja', 'series', '🧽🍍🌊', 1],
  ['Scooby-Doo', 'Scooby-Doo', 'Scooby-Doo', 'series', '🐶👻🚐', 1],
  ['Tom et Jerry', 'Tom and Jerry', 'Tom y Jerry', 'series', '🐱🐭🧀', 1],
  ['Peppa Pig', 'Peppa Pig', 'Peppa Pig', 'series', '🐷🎀🌧️', 1],
  ['Dr House', 'House', 'House', 'series', '💊🩺🦯', 2],
  ['The Big Bang Theory', 'The Big Bang Theory', 'The Big Bang Theory', 'series', '🔬🤓🛋️', 2],
  ['Lost', 'Lost', 'Perdidos', 'series', '✈️🏝️🔢', 2],
  ['Les Pierrafeu', 'The Flintstones', 'Los Picapiedra', 'series', '🦖🪨🚗', 2],
  ['La Chronique des Bridgerton', 'Bridgerton', 'Los Bridgerton', 'series', '👑💃💌', 3],
  ['The Last of Us', 'The Last of Us', 'The Last of Us', 'series', '🍄🧟👧', 3],
  // Video games
  ['Angry Birds', 'Angry Birds', 'Angry Birds', 'game', '🐦😠🐷', 1],
  ['Candy Crush', 'Candy Crush', 'Candy Crush', 'game', '🍬🍭💥', 1],
  ['Mario Kart', 'Mario Kart', 'Mario Kart', 'game', '🏎️🍄🍌', 1],
  ['Just Dance', 'Just Dance', 'Just Dance', 'game', '💃🕺🎵', 1],
  ['Among Us', 'Among Us', 'Among Us', 'game', '🧑‍🚀🔪🟥', 2],
  ['Animal Crossing', 'Animal Crossing', 'Animal Crossing', 'game', '🍃🏝️🦝', 2],
  ['Clash of Clans', 'Clash of Clans', 'Clash of Clans', 'game', '⚔️🏰💰', 2],
  ['Donkey Kong', 'Donkey Kong', 'Donkey Kong', 'game', '🦍🍌🛢️', 2],
  ['Space Invaders', 'Space Invaders', 'Space Invaders', 'game', '👾🚀🕹️', 2],
  ['Les Sims', 'The Sims', 'Los Sims', 'game', '🟢💎🏡', 2],
  // Music
  ['Elvis Presley', 'Elvis Presley', 'Elvis Presley', 'music', '🎸👑🕺', 2],
  ['Mozart', 'Mozart', 'Mozart', 'music', '🎹🎼🇦🇹', 2],
  ['Rihanna', 'Rihanna', 'Rihanna', 'music', '☔💎🎤', 2],
  ['Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'music', '🎸🐍✨', 2],
  ['Shakira', 'Shakira', 'Shakira', 'music', '💃🐺🇨🇴', 2],
  ['Stromae', 'Stromae', 'Stromae', 'music', '🇧🇪🎤🕺', 2],
  ['Céline Dion', 'Céline Dion', 'Céline Dion', 'music', '🚢🎤🇨🇦', 2],
  ['Johnny Hallyday', 'Johnny Hallyday', 'Johnny Hallyday', 'music', '🇫🇷🎸🏍️', 2],
  ['Édith Piaf', 'Édith Piaf', 'Édith Piaf', 'music', '🌹🇫🇷🎤', 2],
  ['Mariah Carey', 'Mariah Carey', 'Mariah Carey', 'music', '🎄🎤❄️', 2],
  // Countries
  ['Portugal', 'Portugal', 'Portugal', 'geo', '🇵🇹🐓', 1],
  ['Belgique', 'Belgium', 'Bélgica', 'geo', '🇧🇪🍟🍫', 1],
  ['Argentine', 'Argentina', 'Argentina', 'geo', '🇦🇷🥩⚽', 1],
  ['Corée du Sud', 'South Korea', 'Corea del Sur', 'geo', '🇰🇷🎤', 1],
  ['Maroc', 'Morocco', 'Marruecos', 'geo', '🇲🇦🫖', 1],
  ['Irlande', 'Ireland', 'Irlanda', 'geo', '🇮🇪☘️', 1],
  ['Norvège', 'Norway', 'Noruega', 'geo', '🇳🇴🌌', 2],
  ['Thaïlande', 'Thailand', 'Tailandia', 'geo', '🇹🇭🏝️', 2],
  // Brands
  ['Adidas', 'Adidas', 'Adidas', 'brand', '👟🇩🇪', 1],
  ['YouTube', 'YouTube', 'YouTube', 'brand', '▶️🔴', 1],
  ['Instagram', 'Instagram', 'Instagram', 'brand', '📸💬❤️', 1],
  ['WhatsApp', 'WhatsApp', 'WhatsApp', 'brand', '💬🟢📞', 1],
  ['TikTok', 'TikTok', 'TikTok', 'brand', '🎵📱🕺', 1],
  ['Burger King', 'Burger King', 'Burger King', 'brand', '👑🍔', 1],
  ['KFC', 'KFC', 'KFC', 'brand', '🍗🪣👴', 1],
  ['Mercedes', 'Mercedes', 'Mercedes', 'brand', '⭐🚗🇩🇪', 2],
  // Nature
  ['Tortue', 'Turtle', 'Tortuga', 'nature', '🐢🏖️', 1],
  ['Singe', 'Monkey', 'Mono', 'nature', '🐒🍌', 1],
  ['Dauphin', 'Dolphin', 'Delfín', 'nature', '🐬🌊', 1],
  ['Loup', 'Wolf', 'Lobo', 'nature', '🐺🌕', 1],
  ['Girafe', 'Giraffe', 'Jirafa', 'nature', '🦒🌳', 1],
  ['Cactus', 'Cactus', 'Cactus', 'nature', '🌵🏜️', 1],
  ['Orage', 'Thunderstorm', 'Tormenta', 'nature', '⚡🌧️', 1],
  ['Tornade', 'Tornado', 'Tornado', 'nature', '🌪️🏠', 2],
  // Food
  ['Omelette', 'Omelette', 'Tortilla francesa', 'food', '🥚🧀🍳', 1],
  ['Salade', 'Salad', 'Ensalada', 'food', '🥗🍅🥒', 1],
  ['Pop-corn', 'Popcorn', 'Palomitas', 'food', '🌽🔥🎬', 1],
  ['Frites', 'Fries', 'Patatas fritas', 'food', '🥔🔥🧂', 1],
  ['Chocolat chaud', 'Hot chocolate', 'Chocolate caliente', 'food', '🍫🥛🔥', 1],
  ['Smoothie', 'Smoothie', 'Batido', 'food', '🍓🍌🥤', 1],
  ['Gaufre', 'Waffle', 'Gofre', 'food', '🧇🍫', 1],
  ['Guacamole', 'Guacamole', 'Guacamole', 'food', '🥑🌶️🇲🇽', 2],
  // Anime
  ['Hello Kitty', 'Hello Kitty', 'Hello Kitty', 'anime', '🐱🎀', 1],
  ['Olive et Tom', 'Captain Tsubasa', 'Oliver y Benji', 'anime', '⚽🇯🇵👦', 2],
  ['Heidi', 'Heidi', 'Heidi', 'anime', '🐐🏔️👧', 2],
  ['Princesse Mononoké', 'Princess Mononoke', 'La princesa Mononoke', 'anime', '🐺👧🌲', 2],
  ['Ponyo', 'Ponyo', 'Ponyo', 'anime', '🐟👧🌊', 2],
  ['Détective Conan', 'Detective Conan', 'Detective Conan', 'anime', '🕵️👓🧒', 2],
  ['Les Chevaliers du Zodiaque', 'Saint Seiya', 'Los Caballeros del Zodiaco', 'anime', '🌌🛡️♈', 3],
  ['Le Château ambulant', 'Howl’s Moving Castle', 'El castillo ambulante', 'anime', '🏰🚶🔥', 3],
];
